In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import make_classification
import keras 
import keras.backend as K
import innvestigate
from keras.models import Model

Using TensorFlow backend.


In [4]:
X, y = make_classification(n_samples=5000, n_features=64, n_informative=1)

In [5]:
#tf.enable_eager_execution()

In [6]:
model = keras.Sequential([
  keras.layers.core.Dense(32, activation=tf.nn.relu6, input_shape=(64,)),  # input shape required
  keras.layers.Dense(16, activation=tf.nn.relu6),
  keras.layers.Dense(2)
])


Instructions for updating:
Colocations handled automatically by placer.


In [7]:
model.compile(optimizer=tf.train.RMSPropOptimizer(0.01),
              loss=keras.losses.categorical_crossentropy,
              metrics=[keras.metrics.categorical_accuracy])

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
le = OneHotEncoder()

le = le.fit(y.reshape(-1,1))
y_bin = le.transform(y.reshape(-1,1))

/home/chschrec/.local/share/virtualenvs/interpret-R0ok2QRq/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [10]:
y_bin.todense()

matrix([[1., 0.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]])

In [11]:
model.fit(X,y_bin.todense(), epochs=30)

Instructions for updating:
Use tf.cast instead.
Epoch 1/30
5000/5000 [==============================] - 1s 128us/step - loss: 0.6818 - categorical_accuracy: 0.7412
Epoch 2/30
5000/5000 [==============================] - 0s 81us/step - loss: 0.4368 - categorical_accuracy: 0.8420
Epoch 3/30
5000/5000 [==============================] - 0s 85us/step - loss: 0.3810 - categorical_accuracy: 0.8864
Epoch 4/30
5000/5000 [==============================] - 0s 73us/step - loss: 0.5969 - categorical_accuracy: 0.9002
Epoch 5/30
5000/5000 [==============================] - 0s 78us/step - loss: 2.7914 - categorical_accuracy: 0.6952
Epoch 6/30
5000/5000 [==============================] - 0s 85us/step - loss: 0.9523 - categorical_accuracy: 0.2190
Epoch 7/30
5000/5000 [==============================] - 0s 79us/step - loss: 0.7668 - categorical_accuracy: 0.2458
Epoch 8/30
5000/5000 [==============================] - 0s 72us/step - loss: 0.5104 - categorical_accuracy: 0.1704
Epoch 9/30
5000/5000 [=========

In [12]:
model.predict(X)

array([[13.441176 , -5.1599417],
       [-2.0514874, 13.707149 ],
       [-2.232689 , 13.950169 ],
       ...,
       [13.741835 , -5.5737376],
       [13.896322 , -6.0910215],
       [ 7.2065725, -4.3314576]], dtype=float32)

In [13]:
analyzer = innvestigate.analyzer.relevance_based.relevance_analyzer.LRPAlpha1Beta0(model)

SyntaxError: invalid syntax (<ipython-input-14-83d675d8cb4c>, line 1)

In [ ]:
analysis = analyzer.analyze(X)

In [ ]:
X

In [ ]:
np.mean(analysis, axis=0)

In [ ]:
model.layers

In [ ]:
analyzer.create_rule_mapping(model.layers[1], )

In [15]:
def cut_last_layer(model, n=1):
    return Model(inputs=model.inputs, outputs=model.layers[-1-n].output)


In [ ]:
analyzer = innvestigate.create_analyzer("lrp.alpha_1_beta_0", cut_last_layer(model, n=1), neuron_selection_mode="index")

In [ ]:
cut_model = cut_last_layer(model, n=1)

In [ ]:
cut_model.compile(optimizer='adagrad').get_layers()

In [ ]:
layer0 = model.layers[0]

In [ ]:
layer0.get_weights()[0]

In [ ]:
layer1.get_weights()[0]

In [ ]:
res = analyzer.analyze(X,31)

In [ ]:
res

In [ ]:
analysis[0]

In [17]:
model = keras.Sequential(layers=[
    keras.layers.Dense(units=32, activation=keras.activations.relu, input_shape=(64,)),
    keras.layers.Dense(units=16, activation=keras.activations.relu),
    keras.layers.Dense(units=2, activation=keras.activations.softmax)
])


In [18]:
model.compile(optimizer='Adam',
              loss=keras.losses.categorical_crossentropy,
              metrics=[keras.metrics.categorical_accuracy])

In [19]:
X_train = X[:4000]

In [20]:
X_test = X[4000:]

In [21]:
y_train = y_bin.todense()[:4000]

In [22]:
y_test = y_bin.todense()[4000:]

In [23]:
model.fit(X_train, y_train, epochs=30)

Epoch 1/30
4000/4000 [==============================] - 1s 159us/step - loss: 0.6286 - categorical_accuracy: 0.6448
Epoch 2/30
4000/4000 [==============================] - 0s 102us/step - loss: 0.4457 - categorical_accuracy: 0.8035
Epoch 3/30
4000/4000 [==============================] - 0s 102us/step - loss: 0.3661 - categorical_accuracy: 0.8423
Epoch 4/30
4000/4000 [==============================] - 0s 98us/step - loss: 0.3214 - categorical_accuracy: 0.8618
Epoch 5/30
4000/4000 [==============================] - 0s 100us/step - loss: 0.2885 - categorical_accuracy: 0.8787
Epoch 6/30
4000/4000 [==============================] - 0s 88us/step - loss: 0.2601 - categorical_accuracy: 0.8915
Epoch 7/30
4000/4000 [==============================] - 0s 84us/step - loss: 0.2375 - categorical_accuracy: 0.9045
Epoch 8/30
4000/4000 [==============================] - 0s 88us/step - loss: 0.2162 - categorical_accuracy: 0.9133
Epoch 9/30
4000/4000 [==============================] - 0s 90us/step - loss:

In [24]:
new_model = innvestigate.utils.model_wo_softmax(model)

In [ ]:
a = innvestigate.analyzer.relevance_based.relevance_analyzer.LRPAlpha1Beta0(new_model, neuron_selection_mode='index')

In [42]:
analysis_n0 = a.analyze(X_test, 0)
analysis_n1 = a.analyze(X_test, 1)

In [41]:
np.sum(np.abs(analysis_n0), axis=0)

array([ 53.501583,  63.029697,  38.36648 ,  64.7435  , 208.21985 ,
        48.924995,  54.769825, 179.79404 , 328.3143  ,  40.79833 ,
        71.938805, 148.84521 ,  58.832596,  49.18619 , 287.95312 ,
        69.019005,  52.56025 ,  53.05498 ,  47.93442 ,  48.929657,
        49.5912  ,  50.070286,  56.063793,  50.4769  , 319.89188 ,
        60.389896,  43.012886,  45.019417,  61.165146,  51.900352,
       157.84258 ,  51.506325,  32.54122 ,  40.803795,  48.52234 ,
        48.459835,  54.71138 ,  55.516914,  57.333797,  69.39263 ,
        57.791077,  45.855473,  43.9796  ,  53.216778,  51.978752,
        46.936935,  47.19524 ,  47.11683 ,  60.253826,  39.386234,
        56.73499 ,  50.994766,  46.701324, 231.34508 ,  55.99102 ,
        55.17115 ,  61.697334,  73.247665,  51.818455, 238.04538 ,
        34.95801 , 159.90387 ,  52.666065,  52.994728], dtype=float32)

In [43]:
np.sum(np.abs(analysis_n1), axis=0)

array([ 53.501583,  63.029697,  38.36648 ,  64.7435  , 208.21985 ,
        48.924995,  54.769825, 179.79404 , 328.3143  ,  40.79833 ,
        71.938805, 148.84521 ,  58.832596,  49.18619 , 287.95312 ,
        69.019005,  52.56025 ,  53.05498 ,  47.93442 ,  48.929657,
        49.5912  ,  50.070286,  56.063793,  50.4769  , 319.89188 ,
        60.389896,  43.012886,  45.019417,  61.165146,  51.900352,
       157.84258 ,  51.506325,  32.54122 ,  40.803795,  48.52234 ,
        48.459835,  54.71138 ,  55.516914,  57.333797,  69.39263 ,
        57.791077,  45.855473,  43.9796  ,  53.216778,  51.978752,
        46.936935,  47.19524 ,  47.11683 ,  60.253826,  39.386234,
        56.73499 ,  50.994766,  46.701324, 231.34508 ,  55.99102 ,
        55.17115 ,  61.697334,  73.247665,  51.818455, 238.04538 ,
        34.95801 , 159.90387 ,  52.666065,  52.994728], dtype=float32)

In [57]:
(np.sum(np.abs(analysis_n0), axis=0) + np.sum(np.abs(analysis_n1), axis=0))

array([129.69539 , 121.3832  ,  85.816635, 130.298   , 554.4561  ,
       107.56642 , 111.01941 , 307.06592 , 737.8342  ,  85.13445 ,
       139.96011 , 369.05423 , 119.1963  , 103.104294, 468.65506 ,
       134.33276 , 112.73964 , 115.37604 , 100.03503 ,  92.04717 ,
       103.10539 , 107.63516 , 112.88361 ,  96.10742 , 568.344   ,
       117.33789 ,  84.95009 ,  92.289215, 125.55323 , 110.57743 ,
       283.91888 , 107.88669 ,  67.991325,  96.782104, 110.178955,
       105.34137 , 116.98128 , 100.9711  , 108.96794 , 143.89973 ,
       124.981186, 104.61773 ,  91.50572 ,  96.78084 , 119.07796 ,
       108.417336,  99.14738 ,  99.23058 , 131.19077 ,  85.4337  ,
       111.84686 , 109.307335,  89.24909 , 512.1564  , 111.19949 ,
       112.11215 , 130.7273  , 151.37524 , 113.43728 , 469.65765 ,
        72.78932 , 358.2037  , 121.94273 , 105.04311 ], dtype=float32)

In [59]:
np.argsort((np.sum(np.abs(analysis_n0), axis=0) + np.sum(np.abs(analysis_n1), axis=0)))

array([32, 60, 26,  9, 49,  2, 52, 42, 19, 27, 23, 43, 33, 46, 47, 18, 37,
       13, 20, 41, 63, 35,  5, 21, 31, 45, 38, 51, 34, 29,  6, 54, 50, 55,
       16, 22, 58, 17, 36, 25, 44, 12,  1, 62, 40, 28,  0,  3, 56, 48, 15,
       10, 39, 57, 30,  7, 61, 11, 14, 59, 53,  4, 24,  8])

In [ ]:
a1 = innvestigate.analyzer.relevance_based.relevance_analyzer.LRPAlpha1Beta0(cut_last_layer(model), neuron_selection_mode='index')

In [ ]:
a1.analyze(X_test, 2)[0]

In [ ]:
a2 = innvestigate.analyzer.relevance_based.relevance_analyzer.LRPAlpha1Beta0(cut_last_layer(model, n=2), neuron_selection_mode='index')

In [ ]:
count = 0
for arr in a2.analyze(X_test, 31):
    if np.sum(arr) == 0:
        count+=1

print(count)

In [ ]:
np.sum(a2.analyze(X_test, 31), axis=0)

In [28]:
(np.sum(a.analyze(X_test, 0), axis=0))

array([ 24.198978 ,   5.4330654,  18.353344 ,  20.21186  , 147.38112  ,
        21.705736 ,  19.620811 ,   1.3526926, 226.99542  ,  17.773066 ,
        13.492573 ,  48.89484  ,  16.189135 ,  17.801525 ,  62.233307 ,
        21.422846 ,  20.286646 ,  22.040644 ,  18.90143  ,   4.624758 ,
        13.392555 ,  17.78278  ,  21.225489 ,  11.659458 ,  98.71338  ,
        15.310058 ,   8.918158 ,   8.277944 ,  16.667187 ,  17.214766 ,
        47.25463  ,  16.840668 ,  10.165367 ,  26.659868 ,  14.637087 ,
        19.321383 ,  18.544174 ,   3.6446671,  11.676939 ,  22.426533 ,
        19.399498 ,  16.564007 ,  17.04478  ,  12.790912 ,  27.558489 ,
        21.002686 ,  13.666864 ,  15.740488 ,  29.78971  ,  10.3110285,
         4.7441134,  21.16869  ,  12.333801 , 157.04886  ,  18.348265 ,
         9.556163 ,  19.191208 ,  23.25707  ,  14.356097 ,  79.90362  ,
         9.877087 ,  67.065315 ,  23.308184 ,  15.463832 ], dtype=float32)

In [ ]:
np.sum(a.analyze(X_test, 1)[0], axis=0)

In [ ]:
a.analyze(X_test, 1)[0]